# CIではSSH cloneができないため、HTTPSを使う

groups:
  - dest: '~/Project1'
    repos:
      - https://github.com/kijimaD/my_go.git
      - https://github.com/kijimaD/gin_hello.git
  - dest: '~/Project2'
    repos:
      - https://github.com/fatih/color.git
      - https://github.com/joho/godotenv.git
