groups:
  - dest: '~/Project1'
    repos:
      - git@github.com:fatih/color.git
      - git@github.com:joho/godotenv.git
  - dest: '~/Project2'
    repos:
      - git@github.com:kijimaD/my_go.git
      - git@github.com:kijimaD/gin_hello.git
