name: ⚗️Check

on:
  push:

jobs:
  # 共通処理
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go
      - name: check out
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@main
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: go build .

  run_exist_dir:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ~/Project1 ~/Project2
      - name: run
        run: go run . -f test/config.yml
      - name: check existing
        run: |
          cd ~/Project1/my_go/.git &&
          cd ~/Project1/gin_hello/.git &&
          cd ~/Project2/color/.git &&
          cd ~/Project2/godotenv/.git

  run_not_exist_dir:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: go run . -f test/config.yml
      - name: check existing
        run: |
          cd ~/Project1/my_go/.git &&
          cd ~/Project1/gin_hello/.git &&
          cd ~/Project2/color/.git &&
          cd ~/Project2/godotenv/.git

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: go test . -v

  # lint:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: v1.29
